services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - WATCHFILES_FORCE_POLLING=true
    command: ["sh", "entrypoint.sh"]
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:     
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db_data:
  es_data:
