"""[add] allow null in event_id

Revision ID: 067f4f701f94
Revises: 587cb08134b2
Create Date: 2025-02-14 20:21:06.527187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '067f4f701f94'
down_revision: Union[str, None] = '587cb08134b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
